[phases.setup]
nixPkgs = ["nodejs_24", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @chatondearu/app build"]

[start]
cmd = "node modules/app/.output/server/index.mjs"
